### PR TITLE
Remove AppCenter API call logic

### LINKED ISSUE #36: [Generalize] Remove AppCenter API call logic

### PR DESCRIPTION
**Pull request by dekim1028**
closes #36 

- Remove logic that calls the AppCenter API

### CODE REVIEW

**Comment by floydkim** [comment]
@dekim1028 
Thank you for your contribution 🎉 
I think we can remove the `code-push` dependency now.
Could you check this?

**Comment by dekim1028** [comment]
@floydkim I've removed it~ https://github.com/Soomgo-Mobile/react-native-code-push/pull/37/commits/febeeeb28f5eb48762e6bf623d6e93cc305d0fbf

**Review by floydkim — APPROVED** [review]
LGTM!

In the future, we plan to re-implement the telemetry functionality we are currently removing and provide library users with the option to implement their own means of telemetry.  
Therefore, I considered leaving the existing telemetry function call code; however, as the existing code is implemented in somewhat legacy syntax and it does not seem difficult to identify the reporting points later, it seems better to cleanly remove the code for now.

**Review by changwoolab — APPROVED** [review]
Good!

**Pull request merged**
